<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\User;
use App\Models\Question;
use App\Models\Category;
use Illuminate\Support\Facades\Hash;
use Carbon\Carbon;
use Illuminate\Support\Str;

class AnalyticsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // 1. Ensure we have at least one Category
        $category = Category::first();
        if (!$category) {
            $category = Category::create([
                'name' => 'General Discussion',
                'slug' => 'general-discussion',
                'acronym' => 'GEN'
            ]);
        }
        
        // Get all category IDs to assign randomly
        $categoryIds = Category::pluck('id')->toArray();

        // 2. Loop through the last 7 days (including today)
        for ($i = 6; $i >= 0; $i--) {
            // Create a timestamp for $i days ago
            $date = now()->subDays($i);
            
            echo "Generating data for: " . $date->format('Y-m-d') . "\n";

            // --- Create Dummy Users (Random 1 to 5 per day) ---
            $userCount = rand(1, 5);
            for ($j = 0; $j < $userCount; $j++) {
                User::create([
                    'name' => "Test User {$i}-{$j}",
                    'email' => "analytics_{$i}_{$j}_" . Str::random(5) . "@example.com",
                    'password' => Hash::make('password'),
                    'member_type' => 'student',
                    'email_verified_at' => $date,
                    'created_at' => $date,
                    'updated_at' => $date,
                ]);
            }

            // --- Create Dummy Questions (Random 5 to 15 per day) ---
            // High variance here will make the chart look more dynamic (zig-zag)
            $questionCount = rand(5, 15);
            
            for ($k = 0; $k < $questionCount; $k++) {
                // Pick a random user and category
                $randomUser = User::inRandomOrder()->first();
                $randomCategory = $categoryIds[array_rand($categoryIds)];
                
                Question::create([
                    'user_id' => $randomUser->id,
                    'category_id' => $randomCategory,
                    'title' => "Test Question for " . $date->format('M d') . " - #" . ($k + 1),
                    'content' => "This is a dummy question generated by the AnalyticsSeeder to test the growth charts. It was created on " . $date->format('Y-m-d'),
                    'views' => rand(5, 500), // Random views for Trending Widget
                    'created_at' => $date,
                    'updated_at' => $date,
                ]);
            }
        }
        
        echo "Analytics data seeding complete!\n";
    }
}